#!/bin/bash
set -euo pipefail

echo "🚀 Installing Infinity Manus Autonomy Framework..."

# Ensure directories
mkdir -p /opt/infinity_x_one/agents/{planner,executor,knowledge,verifier}
chmod -R 755 /opt/infinity_x_one/agents

# Deploy Planner (StrategyGPT)
bash /opt/infinity_x_one/scripts/install_strategy_prompt.sh

# Create placeholder Executor agent
cat << 'EOF' > /opt/infinity_x_one/agents/executor/execute_task.py
#!/usr/bin/env python3
# Autogenerated executor agent
import os, subprocess, json
def run():
    task = os.getenv("NEXT_TASK")
    if task:
        subprocess.run(task, shell=True)
        print("Executed:", task)
if __name__ == "__main__":
    run()
EOF
chmod +x /opt/infinity_x_one/agents/executor/execute_task.py

echo "✅ Infinity Manus framework installed."
