#!/bin/bash
# 🌌 Infinity X One — Nano Super Prompt Daemon
# Auto-reads new GPT projects → builds → wraps → pushes → deploys

DROPZONE="/mnt/gpt_projects"
FACTORY="/opt/infinity_x_one/factory"
TEMPLATES="$FACTORY/templates"
STAGING="$FACTORY/staging"
GLOBAL_ENV="$HOME/.infinity_env"

mkdir -p "$DROPZONE" "$TEMPLATES" "$STAGING"

for SYS in "$DROPZONE"/*; do
  if [ -d "$SYS" ] && [[ ! "$SYS" =~ processed_ ]]; then
    SYS_NAME=$(basename "$SYS")
    REPO_NAME=$(echo "$SYS_NAME" | sed 's/[^a-zA-Z0-9_-]//g')

    echo "🚀 Building new enterprise system: $REPO_NAME"

    DEST="$STAGING/$REPO_NAME"
    mkdir -p "$DEST"

    # Copy GPT drop
    rsync -av "$SYS"/ "$DEST"/
    mv "$SYS" "$DROPZONE/processed_${SYS_NAME}_$(date +%s)"

    # Inject templates
    rsync -av "$TEMPLATES"/ "$DEST"/
    cp "$GLOBAL_ENV" "$DEST/.env"

    # Create README
    cat <<'EOF' > "$DEST/README.md"
# Infinity X One Auto-Built Project

Auto-generated by **Nano SuperPrompt Factory**.
Enterprise-grade, production-ready, plug-and-play.

Includes:
- Global ENV injection
- Supabase schema + RAG
- Omega/CEO Prompt Packs
- Kernel + Orchestration
- Ignite Bootstrap Script
- README + MANIFEST

## Start
```bash
./kernel.sh
